cleaned up gitignore and created history file
osisoft/sample-pi_core-deployment_aws-powershell pull request #2
Opened 2021-08-10 19:50 UTC by kelseyduffy

2021-08-12 20:31 UTC, cbardini approved these changes

2021-08-18 14:15 UTC, dcbroad3 commented
@derekendres Do we want to add the HISTORY and modify .gitignore if we don't really own this sample? This PR would result in a mismatch with what's in ADO.

2021-08-18 19:32 UTC, derekendres approved these changes

2021-08-18 19:33 UTC, derekendres requested changes
probably not

2021-08-20 12:03 UTC, closed without merging